/**
 *
 *  RestfulPastesCtrlBase.h
 *  DO NOT EDIT. This file is generated by drogon_ctl automatically.
 *  Users should implement business logic in the derived class.
 */

#pragma once

#include <drogon/HttpController.h>
#include <drogon/orm/RestfulController.h>
#include <drogon/utils/FunctionTraits.h>

using namespace drogon;
using namespace drogon::orm;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the pastes
 * table.
 */

class RestfulPastesCtrlBase : public RestfulController {
public:
  Task<HttpResponsePtr> getOne(HttpRequestPtr request, const std::string &code);
  Task<HttpResponsePtr> updateOne(HttpRequestPtr request,
                                  const std::string &token);
  Task<HttpResponsePtr> deleteOne(HttpRequestPtr request,
                                  const std::string &token);
  Task<HttpResponsePtr> create(HttpRequestPtr request);

  orm::DbClientPtr getDbClient() {
    return drogon::app().getDbClient(dbClientName_);
  }

protected:
  /// Ensure that subclasses inherited from this class are instantiated.
  RestfulPastesCtrlBase();
  const std::string dbClientName_{"default"};
};
