/**
 *
 *  RestfulPastesCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include "RestfulPastesCtrlBase.h"
#include <drogon/HttpController.h>

#include "Pastes.h"
using namespace drogon;
using namespace drogon_model::pastebin;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the pastes
 * table.
 */

class RestfulPastesCtrl : public drogon::HttpController<RestfulPastesCtrl>,
                          public RestfulPastesCtrlBase {
public:
  METHOD_LIST_BEGIN
  ADD_METHOD_TO(RestfulPastesCtrl::getOne, "/pastes", Get, Options);
  ADD_METHOD_TO(RestfulPastesCtrl::updateOne, "/pastes", Put, Options);
  ADD_METHOD_TO(RestfulPastesCtrl::deleteOne, "/pastes", Delete, Options);
  ADD_METHOD_TO(RestfulPastesCtrl::create, "/pastes", Post, Options);
  // ADD_METHOD_TO(RestfulPastesCtrl::update,"/pastes",Put,Options);
  METHOD_LIST_END

  void getOne(const HttpRequestPtr &request,
              std::function<void(const HttpResponsePtr &)> &&callback);
  void updateOne(const HttpRequestPtr &request,
                 std::function<void(const HttpResponsePtr &)> &&callback);
  void deleteOne(const HttpRequestPtr &request,
                 std::function<void(const HttpResponsePtr &)> &&callback);
  void create(const HttpRequestPtr &request,
              std::function<void(const HttpResponsePtr &)> &&callback);
};
