/**
 *
 *  RestfulPastesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulPastesCtrl.h"
#include <string>

void RestfulPastesCtrl::getOne(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback,
    const std::string &code) {
  RestfulPastesCtrlBase::getOne(request, std::move(callback), code);
}

void RestfulPastesCtrl::updateOne(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback,
    const std::string &token) {
  RestfulPastesCtrlBase::updateOne(request, std::move(callback), token);
}

void RestfulPastesCtrl::deleteOne(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback,
    const std::string &token) {
  RestfulPastesCtrlBase::deleteOne(request, std::move(callback), token);
}

void RestfulPastesCtrl::create(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback) {
  RestfulPastesCtrlBase::create(request, std::move(callback));
}
