/**
 *
 *  RestfulPastesCtrlBase.h
 *  DO NOT EDIT. This file is generated by drogon_ctl automatically.
 *  Users should implement business logic in the derived class.
 */

#pragma once

#include <drogon/HttpController.h>

using namespace drogon;
using namespace drogon::orm;

class RestfulPastesCtrlBase {
public:
  Task<HttpResponsePtr> getOne(HttpRequestPtr request, const std::string &code);
  Task<HttpResponsePtr> updateOne(HttpRequestPtr request,
                                  const std::string &token);
  Task<HttpResponsePtr> deleteOne(HttpRequestPtr request,
                                  const std::string &token);
  Task<HttpResponsePtr> create(HttpRequestPtr request);

  orm::DbClientPtr getDbClient() {
    return drogon::app().getDbClient(dbClientName_);
  }

private:
  const std::string dbClientName_{"pastes-database"};
};
