/**
 *
 *  RestfulPastesCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulPastesCtrl.h"
#include <string>

void RestfulPastesCtrl::getOne(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback) {
  RestfulPastesCtrlBase::getOne(request, std::move(callback),
                                request->getParameter("code"));
}

void RestfulPastesCtrl::updateOne(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback) {
  RestfulPastesCtrlBase::updateOne(request, std::move(callback),
                                   request->getParameter("tojen"));
}

void RestfulPastesCtrl::deleteOne(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback) {
  RestfulPastesCtrlBase::deleteOne(request, std::move(callback),
                                   request->getParameter("token"));
}

void RestfulPastesCtrl::create(
    const HttpRequestPtr &request,
    std::function<void(const HttpResponsePtr &)> &&callback) {
  RestfulPastesCtrlBase::create(request, std::move(callback));
}
